version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: erode_runners_postgres
    environment:
      POSTGRES_USER: eroderunnersclub
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: eroderunnersclub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eroderunnersclub"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: erode_runners_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://eroderunnersclub:securepassword@postgres:5432/eroderunnersclub
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: